### PR TITLE
Added Arawati Website

### PR DESCRIPTION
**Pull request by NaMiKA0305**

### CODE REVIEW

**Comment by NaMiKA0305** [comment]
plzz add this to ur repo

**Comment by Juadebfm** [comment]
Please explain the changes you made before your pull request can be accepted.

**Comment by NaMiKA0305** [comment]
It is a pharmacy website frontpage.named arawati- pharma  it is created by me

**Comment by NaMiKA0305** [comment]
I added this webpage as you mentioned in your issue.

**Comment by Juadebfm** [comment]
I accepted your pull request, but you didn't finish the rules of the repo,
now go back, fork the repo, add your name to the contributor's list
(contributors.md file) and resend the pull request so I can add your name
to the contributor's list. Your the first pull so you'll automatically
become a maintainer when you do this correctly

**Pull request merged**
